#!/usr/bin/env bash
# PreToolUse guard for Edit|Write|MultiEdit.
# Enforces the CLAUDE.md invariants that are hard rules (R1-R5).
# Exit 2 = block; stderr fed back to Claude as the reason.
# Kill switch: set CHORD_DICE_HOOKS_OFF=1 to disable all guards.

set -uo pipefail
[[ "${CHORD_DICE_HOOKS_OFF:-}" == "1" ]] && exit 0

payload=$(cat)

# Robust JSON extraction via python3 (always present on macOS).
read_json() {
  python3 - "$payload" "$1" <<'PY' 2>/dev/null || true
import json, sys
try:
    d = json.loads(sys.argv[1])
except Exception:
    sys.exit(0)
path = sys.argv[2].split(".")
v = d
for p in path:
    if not isinstance(v, dict):
        sys.exit(0)
    v = v.get(p, "")
print(v if v is not None else "")
PY
}

tool=$(read_json "tool_name")
file_path=$(read_json "tool_input.file_path")

# Collect the text being written across Write/Edit/MultiEdit.
new_text=$(python3 - "$payload" <<'PY' 2>/dev/null || true
import json, sys
try:
    d = json.loads(sys.argv[1])
except Exception:
    sys.exit(0)
t = d.get("tool_name")
ti = d.get("tool_input", {}) or {}
if t == "Write":
    print(ti.get("content", "") or "")
elif t == "Edit":
    print(ti.get("new_string", "") or "")
elif t == "MultiEdit":
    parts = [e.get("new_string", "") for e in ti.get("edits", []) if isinstance(e, dict)]
    print("\n".join(parts))
PY
)

block() {
  echo "$1" >&2
  exit 2
}

# Allow writes from outside the project tree unconditionally.
[[ -z "$file_path" ]] && exit 0

# R1 — Block hand-edits to generated *.g.dart files.
if [[ "$file_path" == *.g.dart ]]; then
  block "BLOCKED (R1): $file_path is generated by riverpod_generator / build_runner. Regenerate with:
  dart run build_runner build --delete-conflicting-outputs
Never hand-edit *.g.dart — see CLAUDE.md (Riverpod codegen contract)."
fi

# R2 — Block banned dependencies in pubspec.yaml.
if [[ "$file_path" == *pubspec.yaml ]]; then
  if printf '%s' "$new_text" | grep -Eq '^[[:space:]]*(google_fonts|equatable|flame|flame_audio)[[:space:]]*:'; then
    block "BLOCKED (R2): This project forbids:
  • google_fonts — removed deliberately, typography is plain MD3.
  • equatable — immutable models use manual == / hashCode via Object.hash.
  • flame / flame_audio — CustomPainter is the chosen path for dice rendering.
See CLAUDE.md (Conventions & gotchas)."
  fi
fi

# R3 — Block StateNotifier reintroduction inside lib/.
if [[ "$file_path" == *lib/*.dart ]]; then
  if printf '%s' "$new_text" | grep -Eq '\bStateNotifier(Provider)?\b'; then
    block "BLOCKED (R3): All 8 providers migrated to @Riverpod(keepAlive: true) class codegen Notifiers. Do not reintroduce StateNotifier / StateNotifierProvider."
  fi
fi

# R4 — Block lint-ignore comments in lib/ and test/ (zero-issue rule).
if [[ "$file_path" == *lib/*.dart || "$file_path" == *test/*.dart ]]; then
  if printf '%s' "$new_text" | grep -Eq '//[[:space:]]*ignore(_for_file)?:'; then
    block "BLOCKED (R4): CLAUDE.md requires flutter analyze stay zero-issue. '// ignore:' and '// ignore_for_file:' are how a zero-issue rule silently rots. Fix the root cause instead. If you truly need an exception, set CHORD_DICE_HOOKS_OFF=1 for this turn and document why."
  fi
fi

# R5 — Block hardcoded colors in widgets/ and screens/. Theme files exempt.
if [[ "$file_path" == *lib/widgets/*.dart || "$file_path" == *lib/screens/*.dart ]]; then
  if printf '%s' "$new_text" | grep -Eq 'Color\(0x[0-9A-Fa-f]{8}\)|\bColors\.(red|blue|green|amber|yellow|orange|pink|purple|teal|cyan|indigo|lime|deepOrange|deepPurple|lightBlue|lightGreen|brown|grey|gray|black|white)\b'; then
    block "BLOCKED (R5): Do not hardcode colors in widgets/ or screens/. Pull from Theme.of(context).colorScheme — every palette derives from ColorScheme.fromSeed() via buildTheme(). D20 accent = colorScheme.primary; D12 accent = colorScheme.secondary. See CLAUDE.md (Theme settings) and lib/theme.dart."
  fi
fi

exit 0
