services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: notely
      POSTGRES_PASSWORD: notely
      POSTGRES_DB: notely
    ports:
      - "5453:5432"
    volumes:
      - notely_db_data:/var/lib/postgresql/data

volumes:
  notely_db_data:
