import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored design system (generated by claude design). The upstream
    // reference is read-only; the live copies under components/ds/ are
    // verbatim adaptations (only 'use client' added). Linting them would
    // fork the kit, so they are excluded — my authored code (app/, lib/,
    // scripts/, evals/) is fully linted. See DESIGN.md.
    "docs/design-system/**",
    "components/ds/**",
  ]),
]);

export default eslintConfig;
