// Design-system primitives barrel — every screen composes these instead of re-inventing chrome.
export { default as AppIcon, type IconName } from './AppIcon.vue'
export { default as StatusDot, type StatusTone } from './StatusDot.vue'
export { default as BaseChip, type ChipVariant } from './BaseChip.vue'
export { default as BaseCard } from './BaseCard.vue'
export { default as BaseButton, type ButtonVariant } from './BaseButton.vue'
export { default as ProgressBar } from './ProgressBar.vue'
export { default as SegmentedControl, type SegmentOption } from './SegmentedControl.vue'
export { default as BaseStepper } from './BaseStepper.vue'
export { default as BaseToggle } from './BaseToggle.vue'
export { default as LoadingSpinner } from './LoadingSpinner.vue'
export { default as EmptyState } from './EmptyState.vue'
export { default as NavSidebar } from './NavSidebar.vue'
export { default as BottomNav } from './BottomNav.vue'
export { default as OfflineBanner } from './OfflineBanner.vue'
export { default as SidebarLink } from './SidebarLink.vue'
export { default as KeepReadingCard } from './KeepReadingCard.vue'
export { default as RecentlyCoverCard } from './RecentlyCoverCard.vue'
