using System.Text;
using System.Text.RegularExpressions;

var root = Environment.CurrentDirectory;
var requirementsPath = Path.Combine(root, "docs", "requirements.md");
var specsRoot = Path.Combine(root, "openspec", "specs");
var outputPath = Path.Combine(root, "qa", "traceability-matrix.md");

var requirementRows = ParseRequirements(File.ReadAllText(requirementsPath));
var specCitations = BuildSpecCitationMap(specsRoot);
var traceHits = BuildTraceMap(root);
var sliceOwners = BuildSliceOwnerMap();

var sb = new StringBuilder();
sb.AppendLine("# Traceability Matrix");
sb.AppendLine();
sb.AppendLine("Generated by `scripts/generate-traceability-matrix.cs` on "
    + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm") + " UTC.");
sb.AppendLine();
sb.AppendLine("| ID | Kind | Req. status | OpenSpec | Slice | Tests / evals (@trace) | Verdict |");
sb.AppendLine("| --- | --- | --- | --- | --- | --- | --- |");

foreach (var row in requirementRows.OrderBy(row => row.Id))
{
    specCitations.TryGetValue(row.Id, out var specs);
    traceHits.TryGetValue(row.Id, out var traces);
    sliceOwners.TryGetValue(row.Id, out var slice);

    sb.Append('|').Append(' ').Append(row.Id).Append(" | ");
    sb.Append(row.Kind).Append(" | ");
    sb.Append(row.Status).Append(" | ");
    sb.Append(specs is null || specs.Count == 0 ? "—" : string.Join(", ", specs)).Append(" | ");
    sb.Append(slice ?? "—").Append(" | ");
    sb.Append(traces is null || traces.Count == 0 ? "—" : string.Join("; ", traces.Take(4))).Append(" | ");
    sb.Append(MapVerdict(slice)).Append(" |");
    sb.AppendLine();
}

sb.AppendLine();
sb.AppendLine("## Notes");
sb.AppendLine();
sb.AppendLine("- **OpenSpec** paths are relative to `openspec/specs/`.");
sb.AppendLine("- **Tests / evals** lists representative `@trace` anchors; run the generator after adding coverage.");
sb.AppendLine("- Cross-cutting constraints (`TC-*`, `BC-*`) are verified by gates and architecture reviews across slices.");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Wrote {outputPath} ({requirementRows.Count} rows).");
return 0;

static List<RequirementRow> ParseRequirements(string markdown)
{
    var rows = new List<RequirementRow>();
    var currentKind = "FR";

    foreach (var line in markdown.Split('\n'))
    {
        if (line.StartsWith("## Functional Requirements", StringComparison.Ordinal))
        {
            currentKind = "FR";
            continue;
        }

        if (line.StartsWith("## Non-Functional Requirements", StringComparison.Ordinal))
        {
            currentKind = "NFR";
            continue;
        }

        if (line.StartsWith("## Technical Constraints", StringComparison.Ordinal))
        {
            currentKind = "TC";
            continue;
        }

        if (line.StartsWith("## Business Constraints", StringComparison.Ordinal))
        {
            currentKind = "BC";
            continue;
        }

        var match = Regex.Match(line, @"^\|\s*(?<id>(?:FR|NFR|TC|BC)-[A-Z]+-\d{2})\s*\|\s*(?<status>\w+)\s*\|");
        if (!match.Success)
        {
            continue;
        }

        rows.Add(new RequirementRow(match.Groups["id"].Value, currentKind, match.Groups["status"].Value));
    }

    return rows;
}

static Dictionary<string, List<string>> BuildSpecCitationMap(string specsRoot)
{
    var map = new Dictionary<string, List<string>>(StringComparer.Ordinal);

    foreach (var specPath in Directory.EnumerateFiles(specsRoot, "spec.md", SearchOption.AllDirectories))
    {
        var relative = Path.GetRelativePath(specsRoot, specPath).Replace('\\', '/');
        var text = File.ReadAllText(specPath);

        foreach (Match match in Regex.Matches(text, @"`(FR-[A-Z]+-\d{2}|NFR-[A-Z]+-\d{2}|TC-[A-Z]+-\d{2}|BC-[A-Z]+-\d{2})`"))
        {
            if (!map.TryGetValue(match.Groups[1].Value, out var specs))
            {
                specs = [];
                map[match.Groups[1].Value] = specs;
            }

            if (!specs.Contains(relative))
            {
                specs.Add(relative);
            }
        }
    }

    return map;
}

static Dictionary<string, List<string>> BuildTraceMap(string root)
{
    var map = new Dictionary<string, List<string>>(StringComparer.Ordinal);
    var searchRoots = new[]
    {
        Path.Combine(root, "src"),
        Path.Combine(root, "tests"),
        Path.Combine(root, "evals"),
    };

    foreach (var searchRoot in searchRoots.Where(Directory.Exists))
    {
        foreach (var file in Directory.EnumerateFiles(searchRoot, "*.*", SearchOption.AllDirectories)
                     .Where(path => path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)))
        {
            var relative = Path.GetRelativePath(root, file).Replace('\\', '/');
            var text = File.ReadAllText(file);

            foreach (Match match in Regex.Matches(text, @"@trace\s+([^""\n]+)"))
            {
                foreach (Match idMatch in Regex.Matches(match.Groups[1].Value, @"\b(?:FR|NFR|TC|BC)-[A-Z]+-\d{2}\b"))
                {
                    if (!map.TryGetValue(idMatch.Value, out var hits))
                    {
                        hits = [];
                        map[idMatch.Value] = hits;
                    }

                    if (!hits.Contains(relative))
                    {
                        hits.Add(relative);
                    }
                }
            }
        }
    }

    return map;
}

static Dictionary<string, string> BuildSliceOwnerMap() => new(StringComparer.Ordinal)
{
    ["FR-PREPROC-01"] = "core-preprocessing",
    ["FR-PREPROC-02"] = "core-preprocessing",
    ["FR-PREPROC-03"] = "core-preprocessing",
    ["FR-DETECT-01"] = "core-inference",
    ["FR-DETECT-02"] = "core-inference",
    ["FR-DETECT-03"] = "core-inference",
    ["FR-OVERLAY-01"] = "core-overlay",
    ["FR-OVERLAY-02"] = "app-ui",
    ["FR-CAPTURE-01"] = "app-ui",
    ["FR-PICK-01"] = "app-ui",
    ["FR-MCP-01"] = "mcp-server",
    ["FR-MCP-02"] = "mcp-server",
    ["NFR-PERF-01"] = "app-ui",
    ["NFR-STARTUP-01"] = "app-ui",
    ["NFR-TEST-01"] = "evals-hardening",
    ["NFR-EVAL-01"] = "evals-hardening",
    ["TC-STACK-01"] = "cross-cutting",
    ["TC-ARCH-01"] = "cross-cutting",
    ["TC-MODEL-01"] = "cross-cutting",
    ["TC-MODEL-02"] = "cross-cutting",
    ["TC-SPEC-01"] = "cross-cutting",
    ["BC-OFFLINE-01"] = "cross-cutting",
    ["BC-PRIVACY-01"] = "cross-cutting",
    ["BC-SCOPE-01"] = "cross-cutting",
};

static string MapVerdict(string? slice) => slice switch
{
    "core-preprocessing" => "[core-preprocessing](verdicts/core-preprocessing.md)",
    "core-inference" => "[core-inference](verdicts/core-inference.md)",
    "core-overlay" => "[core-overlay](verdicts/core-overlay.md)",
    "app-ui" => "[app-ui](verdicts/app-ui.md)",
    "mcp-server" => "[mcp-server](verdicts/mcp-server.md)",
    "evals-hardening" => "[evals-hardening](verdicts/evals-hardening.md)",
    "cross-cutting" => "gates / ADRs",
    _ => "—",
};

file sealed record RequirementRow(string Id, string Kind, string Status);
